DROP TABLE IF EXISTS courses;
CREATE TABLE courses (
id INTEGER PRIMARY KEY,
name TEXT DEFAULT NULL, 
teacher_id INTEGER NOT NULL
);

DROP TABLE IF EXISTS grades;
CREATE TABLE grades (
student_id INTEGER NOT NULL, 
course_id INTEGER NOT NULL, 
grade varchar(2) DEFAULT NULL
);

DROP TABLE IF EXISTS students;
CREATE TABLE students (
id INTEGER PRIMARY KEY,
name TEXT DEFAULT NULL, 
email TEXT DEFAULT NULL,
password TEXT DEFAULT NULL
);

DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers (
id INTEGER PRIMARY KEY,
name TEXT DEFAULT NULL
);